### PR TITLE
Duplicate Error fix (closes #17)

### LINKED ISSUE #17: Add a check for the existence of a user with the same name when editing
When creating a user, there is a check for the existence of a user with the same name, a warning is displayed.
Should be the same when editing.
If a user with this name exists, a warning is shown, when you click on Save again, the user's data is changed

### PR DESCRIPTION
**Pull request by viktoria2506**
Handled a case when, when editing, a user with a new name already exists

### CODE REVIEW

File: src/actions/user-action.js [hunk 1]
```diff
@@ -10,10 +10,11 @@ class UserAction {
         });
     }
 
-    updateUser (user) {
+    updateUser (user, force) {
         Dispatcher.dispatch({
             ACTION_TYPE: ACTION_TYPE.updateUser,
-            user:        user
+            user:        user,
+            force: force
```
Comment (Dmitry-Ostashev) [inline src/actions/user-action.js]: [minor code style suggestion]

The modern JS syntax allows us to define objects by the following way:

```
Dispatcher.dispatch({
            ACTION_TYPE: ACTION_TYPE.updateUser,

            user,
            force
});
```

I.e. if the names of the object's property and the variable you're passing as its value are the same, you may specify it once.

File: src/components/editing-buttons.js [hunk 2]
```diff
@@ -22,14 +24,21 @@ export default class EditingButtons extends React.Component {
...
+        const { currentUser, hasDuplicateError } = this.props;
+        const newUser                            = new UserInfo(currentUser.info, currentUser.address, currentUser.company);
 
-        UserAction.updateUser(newUser);
-        onChange({ mode: MODES.default, currentUser });
+        UserAction.updateUser(newUser, hasDuplicateError);
         e.preventDefault();
     };
 
+    _updateFailed = (userId) => {
```
Comment (Dmitry-Ostashev) [inline src/components/editing-buttons.js]: Let's add the `on` prefix for event handlers, e.g. `_onUpdateFailed`. Otherwise, if the method isn't handler, its name should mean some kind of action, e.g. "doSomething()".

File: src/components/user-list.js [hunk 3]
```diff
@@ -35,7 +35,8 @@ export default class UserList extends React.Component {
     };
 
     _addingFailed = (userId) => {
-        this.setState({ duplicateUserId: userId });
+        debugger;
```
Comment (Dmitry-Ostashev) [inline src/components/user-list.js]: Forgotten `debugger`

File: src/components/user.js [hunk 4]
```diff
@@ -59,10 +61,25 @@ export default class User extends React.Component {
             showAddress:       false,
             showCompany:       false,
             hasDuplicateError: false,
+            duplicateUserId:   '',
             mode:              isNewUser ? MODES.new : MODES.default
         };
     }
 
+    componentWillUnmount () {
+        UserStore.off(EVENT_TYPE.updateFailed, this._updateFailed);
```
Comment (Dmitry-Ostashev) [inline src/components/user.js]: See the previous comment about handler names.

**Review by Dmitry-Ostashev — CHANGES_REQUESTED** [review]
There is an error in the console after some manipulations (e.g. adding new user):

image

You may google the reason of such errors.
Let's fix it.

**Review by Dmitry-Ostashev — APPROVED** [review]
Let's get it work.
